version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Berlin
  target-branch: develop
  reviewers:
  - lkochniss
  ignore:
  - dependency-name: aws/aws-sdk-php
    versions:
    - 3.178.1
  - dependency-name: symfony/yaml
    versions:
    - 4.4.18
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/dotenv
    versions:
    - 4.4.18
    - 4.4.19
  - dependency-name: symfony/asset
    versions:
    - 4.4.18
    - 4.4.19
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    timezone: Europe/Berlin
  target-branch: develop
  ignore:
  - dependency-name: webpack-assets-manifest
    versions:
    - 4.0.4
  - dependency-name: css-loader
    versions:
    - 5.2.1
  - dependency-name: bootstrap
    versions:
    - 4.6.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
    - 4.6.0
  - dependency-name: d3
    versions:
    - 6.5.0
    - 6.6.0
    - 6.6.1
  - dependency-name: url-loader
    versions:
    - 4.1.1
