framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection: true
    #http_method_override: true
    #trusted_hosts: ~
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
    #    # The native PHP session handler will be used
        handler_id: ~
        cookie_lifetime: 604800
        cookie_httponly: true
        cookie_samesite: 'strict'
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    assets:
        json_manifest_path: '%kernel.root_dir%/../public/manifest.json'
