php_version: 7.1

# Configure rules.
rules:
    # Disable a rule
    php.class_too_long:
        enabled: false

    # Configure a rule
    php.class_too_long:
        max_length: 2000
        threshold:  10

pre_composer_script: |
    #!/bin/bash

    cp .env.dist .env
