# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: zaherg/php-7.2-xdebug-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: composer install
          command: composer install --no-interaction --prefer-dist --no-scripts --no-progress

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - run:
          name: copy environmenmt
          command: cp .env.dist .env

      - run:
          name: Clear Cache
          command: bin/console cache:clear

      - run:
          name: Creating Artifacts Directory
          command: mkdir /tmp/artifacts;

      - run:
          name: Run UnitTests
          command: vendor/bin/phpunit --coverage-html /tmp/artifacts/phpunit/ --colors=never

      - store_artifacts:
          path: /tmp/artifacts
