# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ckappen/php-composer-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Composer Install
          command: composer install --no-interaction --prefer-dist --no-scripts --no-progress
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}
      - run:
          name: Copy Environmenmt
          command: make copy-ci-environment
      - run:
          name: Create Artifacts Directory
          command: make build-artifacts
      - run:
          name: Clear Cache
          command: make cache
      - run:
          name: CodeSniff
          command: make codesniff
      - run:
          name: Copy & Paste
          command: make copypaste
      - run:
          name: Lines of Code
          command: make lines
      - run:
          name: Mess Detector
          command: make copypaste
      - run:
          name: PHPStan
          command: make phpstan
      - run:
          name: Run UnitTests
          command: make phpunit
      - store_artifacts:
          path: build-artifacts/
