# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

php-docker-image: &php-docker-image
  docker:
    - image: lkochniss/php7-for-circleci-and-development

attach_whole_workspace: &attach_whole_workspace
  attach_workspace:
    at: ~/project

persist_whole_workspace: &persist_whole_workspace
  persist_to_workspace:
    root: ~/project
    paths: .

jobs:

  checkout:
    <<: *php-docker-image
    steps:
      - checkout
      - *persist_whole_workspace


  php-get-composer-vendors:
    <<: *php-docker-image
    steps:
      - *attach_whole_workspace

      - restore_cache:
          keys:
          - php-composer-dependencies-{{ checksum "composer.lock" }}

      - run:
          name: Install dev dependencies
          command: composer install --no-progress --prefer-dist --no-scripts

      - save_cache:
          paths: vendor
          key: php-composer-dependencies-{{ checksum "composer.lock" }}

      - *persist_whole_workspace

  php-static-code-analysis:
    <<: *php-docker-image
    working_directory: /tmp/php-static-code-analysis
    steps:
      - attach_workspace:
          at: /tmp/php-static-code-analysis

      - run:
          name: Copy Environment
          command: cp .env.circleci .env

      - run:
          name: Launch php-linting
          command: ./vendor/bin/phplint

      - run:
          name: Launch Code Sniffer
          command: ./vendor/bin/phpcs --standard=PSR1,PSR2 --ignore=src/Migrations -s src/  -s tests/

      - run:
          name: Launch Security Checker
          command: ./vendor/bin/security-checker security:check

      - run:
          name: Launch Copy & Paste Detection
          command: ./vendor/bin/phpcpd src || true

      - run:
          name: Launch Mess Detection Suite
          command: ./.circleci/php-mess-detection.sh

  php-unittests:
    <<: *php-docker-image
    steps:
      - *attach_whole_workspace

      - run:
          name: Copy Environment
          command: cp .env.circleci .env

      - run:
          name: Create fake manifest.json
          command: echo {} >> public/manifest.json

      - run:
          name: Launch Unit tests
          command: ./.circleci/php-unit-tests.sh

      - run:
          name: delete fake manifest.json again to not interfere with the correct one
          command: rm public/manifest.json

      - *persist_whole_workspace
      - store_artifacts:
          path: var/log/test.log

  send-code-coverage:
    <<: *php-docker-image
    steps:
      - *attach_whole_workspace
      - run:
         name: Send CodeCov to codacy
         command: ./vendor/bin/codacycoverage clover build/cloverreport.xml

workflows:
  version: 2
  test_and_analyse:
    jobs:

      - checkout

      - php-get-composer-vendors:
          requires:
            - checkout

      - php-static-code-analysis:
          requires:
            - php-get-composer-vendors

      - php-unittests:
          requires:
            - php-get-composer-vendors

      - send-code-coverage:
          requires:
            - php-unittests
