sessions_this_year:
    path:   /sessions/this-year
    defaults: { _controller: 'App\Controller\ApiController::sessionsThisYear'  }

sessions_per_month:
    path:   /sessions/per-month
    defaults: { _controller: 'App\Controller\ApiController::sessionsPerMonth'  }

average_per_month:
    path:   /average/per-month
    defaults: { _controller: 'App\Controller\ApiController::averagePerMonth'  }

sessions_last_week:
    path:   /sessions/recently
    defaults: { _controller: 'App\Controller\ApiController::sessionsLastDays'  }

sessions_for_game:
    path:   /sessions/game/{id}
    defaults: { _controller: 'App\Controller\ApiController::sessionsForGame'  }

sessions_per_month_for_game:
    path:   /sessions/game/{id}/per-month
    defaults: { _controller: 'App\Controller\ApiController::sessionsPerMonthForGame'  }

sessions_for_year:
    path:   /sessions/{year}
    defaults: { _controller: 'App\Controller\ApiController::sessionsForYear'  }
