sessions_per_month:
    path:   /sessions/per-month
    defaults: { _controller: 'App\Controller\ApiController::sessionsPerMonth'  }

sessions_last_week:
    path:   /sessions/recently
    defaults: { _controller: 'App\Controller\ApiController::sessionsLastDays'  }
