sessions_per_month:
    path:   /sessions
    defaults: { _controller: 'App\Controller\ApiController::sessionsPerMonth'  }

sessions_last_week:
    path:   /last-week
    defaults: { _controller: 'App\Controller\ApiController::sessionsLastDays'  }
