sessions_per_month:
    path:   /sessions/per-month
    defaults: { _controller: 'App\Controller\ApiController::sessionsPerMonth'  }

sessions_last_week:
    path:   /sessions/recently
    defaults: { _controller: 'App\Controller\ApiController::sessionsLastDays'  }

sessions_for_game:
    path:   /sessions/game/{id}
    defaults: { _controller: 'App\Controller\ApiController::sessionsForGame'  }

invested_money_per_month:
    path:   /money/per-month
    defaults: { _controller: 'App\Controller\ApiController::investedMoneyPerMonth'  }
