game_status_open:
    path: /game/{id}/status/open
    defaults: { _controller: 'App\Controller\GameStatsController::setStatusOpen' }

game_status_paused:
    path: /game/{id}/status/paused
    defaults: { _controller: 'App\Controller\GameStatsController::setStatusPaused' }

game_status_playing:
    path: /game/{id}/status/playing
    defaults: { _controller: 'App\Controller\GameStatsController::setStatusPlaying' }

game_status_finished:
    path: /game/{id}/status/finished
    defaults: { _controller: 'App\Controller\GameStatsController::setStatusFinished' }

game_status_given_up:
    path: /game/{id}/status/given-up
    defaults: { _controller: 'App\Controller\GameStatsController::setStatusGivenUp' }
