game_list:
    path: /game
    defaults: { _controller: 'App\Controller\GameController::list' }
game_update_steam_information:
    path: /game/{id}/update
    defaults: { _controller: 'App\Controller\GameController::update' }
game_dashboard:
    path: /game/{id}/dashboard
    defaults: { _controller: 'App\Controller\GameController::dashboard' }
