game_session_list_backend:
    path: /session
    defaults: { _controller: 'App\Controller\GameSessionController::listBackend' }
game_session_list_for_game:
    path: /game/{id}/session
    defaults: { _controller: 'App\Controller\GameSessionController::listBackendForGame' }
