game_session_list:
    path: /session
    defaults: { _controller: 'App\Controller\GameSessionController::list' }
game_session_list_for_game:
    path: /game/{id}/session
    defaults: { _controller: 'App\Controller\GameSessionController::listForGame' }
