game_list:
    path: /game
    defaults: { _controller: 'App\Controller\GameController::list' }

game_dashboard:
    path: /game/{id}/dashboard
    defaults: { _controller: 'App\Controller\GameController::dashboard' }
