homepage_dashboard:
    path: /
    defaults: { _controller: 'App\Controller\HomepageController::dashboard' }

homepage_impersonate:
    path: /users
    defaults: { _controller: 'App\Controller\HomepageController::selectImpersonate' }
