homepage_recently_played:
    path: /
    defaults: { _controller: 'App\Controller\HomepageController::recentlyPlayed' }
homepage_most_played:
    path: /top
    defaults: { _controller: 'App\Controller\HomepageController::mostPlayed' }
homepage_newest_games:
    path: /new
    defaults: { _controller: 'App\Controller\HomepageController::newGames' }
