purchase_list_backend:
    path: /purchase
    defaults: { _controller: 'App\Controller\PurchaseController::listBackend' }
purchase_create_for_game:
    path: /game/{id}/purchase/create
    defaults: { _controller: 'App\Controller\PurchaseController::createForGame' }
purchase_list_for_game:
    path: /game/{id}/purchase
    defaults: { _controller: 'App\Controller\PurchaseController::listBackendForGame' }
purchase_create:
    path: /purchase/create
    defaults: { _controller: 'App\Controller\PurchaseController::create' }
purchase_edit:
    path: /purchase/{id}/edit
    defaults: { _controller: 'App\Controller\PurchaseController::edit' }
