## Api
api_admin:
    resource: routing/api.yaml
    prefix: /api

## Login
secruity_admin:
    resource: routing/security.yaml

steam_admin:
    resource: routing/steam.yaml

## Homepage

homepage_backend:
    resource: routing/homepage.yaml
    trailing_slash_on_root: false

## Game
game_admin:
    resource: routing/game.yaml

game_stats:
    resource: routing/game_stats.yaml

## Purchase
game_session_admin:
    resource: routing/game_session.yaml
