index:
    path: /
    defaults: { _controller: 'App\Controller\AppController::index' }
blog_list:
    path: /blog
    defaults: { _controller: 'App\Controller\BlogController::list' }
blog_create:
    path: /blog/create
    defaults: { _controller: 'App\Controller\BlogController::create' }
blog_edit:
    path: /blog/{id}/edit
    defaults: { _controller: 'App\Controller\BlogController::edit' }
blog_show:
    path: /blog/{id}/show
    defaults: { _controller: 'App\Controller\BlogController::show' }
