## Api
api_admin:
    resource: routing/api.yaml

## Login
secruity_admin:
    resource: routing/security.yaml

steam_admin:
    resource: routing/steam.yaml

## Homepage

homepage_backend:
    resource: routing/homepage.yaml
    trailing_slash_on_root: false

## Game
game_admin:
    resource: routing/game.yaml

## Purchase
purchase_admin:
    resource: routing/purchase.yaml

## Purchase
game_session_admin:
    resource: routing/game_session.yaml
