# Admin

## Login
secruity_admin:
    resource: routing/security_admin.yaml
    prefix: /admin

## Game
game_admin:
    resource: routing/game_admin.yaml
    prefix: /admin

## BlogPost
blog_post_admin:
    resource: routing/blog_post_admin.yaml
    prefix: /admin

## Purchase
purchase_admin:
    resource: routing/purchase_admin.yaml
    prefix: /admin

# Frontend

## Homepage
homepage_frontend:
    resource: routing/homepage_frontend.yaml

## Game
game_frontend:
    resource: routing/game_frontend.yaml

## BlogPost
blog_post_frontend:
    resource: routing/blog_post_frontend.yaml
