# Security
login:
    path:   /admin/login
    defaults: { _controller: 'App\Controller\SecurityController::login'  }
login_check:
    path:   /admin/login_check
logout:
    path:   /admin/logout

# Homepage
recentlyPlayed:
    path: /
    defaults: { _controller: 'App\Controller\AppController::recentlyPlayed' }
mostPlayed:
    path: /top
    defaults: { _controller: 'App\Controller\AppController::mostPlayed' }

# BlogPost
blog_list:
    path: /admin/blog
    defaults: { _controller: 'App\Controller\BlogPostController::list' }
blog_create:
    path: /admin/blog/create
    defaults: { _controller: 'App\Controller\BlogPostController::create' }
blog_edit:
    path: /admin/blog/{id}/edit
    defaults: { _controller: 'App\Controller\BlogPostController::edit' }
blog_show:
    path: /blog/{id}/show
    defaults: { _controller: 'App\Controller\BlogPostController::show' }
