App\Entity\Achievement:
    type: entity
    repositoryClass: App\Repository\AchievementRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        playerAchievements:
            type: integer
            column: player_achievements
        overallAchievements:
            type: integer
            column: overall_achievements
        steamUserId:
            type: integer
            column: steam_user_id
    manyToOne:
          game:
              targetEntity: Game
              joinColumn:
                  name: game_id
                  referenceColumnName: id
