App\Entity\BlogPost:
    type: entity
    repositoryClass: App\Repository\BlogPostRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 100
        content:
            type: text
    manyToOne:
        game:
            targetEntity: Game
            inversedBy: blogPosts
            joinColumn:
                name: game_id
                referencedColumnName: id
