App\Entity\Game:
    type: entity
    repositoryClass: App\Repository\GameRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        steamAppId:
            column: steam_app_id
            type: integer
            nullable: false
        name:
            type: string
            nullable: false
            length: 100
        timePlayed:
            column: time_played
            type: integer
            nullable: false
        recentlyPlayed:
            column: recently_played
            type: integer
            nullable: false
        headerImagePath:
            column: header_image_path
            type: string
    oneToMany:
          blogPosts:
              targetEntity: BlogPost
              mappedBy: game
    lifecycleCallbacks:
          prePersist:
                  - setModifiedAt
                  - setCreatedAt
          preUpdate:
                  - setModifiedAt
