App\Entity\GameSession:
    type: entity
    repositoryClass: App\Repository\GameSessionRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        duration:
            type: integer
    manyToOne:
        game:
            targetEntity: Game
            inversedBy: gameSessions
            joinColumn:
                name: game_id
                referencedColumnName: id
    lifecycleCallbacks:
          prePersist:
                  - setModifiedAt
                  - setCreatedAt
          preUpdate:
                  - setModifiedAt
