App\Entity\GameSession:
    type: entity
    repositoryClass: App\Repository\GameSessionRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        duration:
            type: integer
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referenceColumnName: id
        game:
            targetEntity: Game
            inversedBy: gameSessions
            joinColumn:
                name: game_id
                referencedColumnName: id
