App\Entity\GameStats:
    type: entity
    repositoryClass: App\Repository\GameStatsRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        status:
            type: string
            nullable: false
        steamUserId:
            type: bigint
            column: steam_user_id
    manyToOne:
        achievement:
            targetEntity: Achievement
            cascade: ["persist", "refresh"]
            joinColumn:
                name: achievement_id
                referencedColumnName: id
        playtime:
            targetEntity: Playtime
            cascade: ["persist", "refresh"]
            joinColumn:
                name: playtime_id
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referenceColumnName: id
        game:
            targetEntity: Game
            joinColumn:
                name: game_id
                referencedColumnName: id

