App\Entity\Game:
    type: entity
    repositoryClass: App\Repository\GameRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        steamAppId:
            column: steam_app_id
            type: integer
            nullable: false
        name:
            type: string
            nullable: false
            length: 100
        timePlayed:
            column: time_played
            type: integer
            nullable: false
        recentlyPlayed:
            column: recently_played
            type: integer
            nullable: false
        headerImagePath:
            column: header_image_path
            type: string
        boughtAt:
            column: bought_at
            type: datetime
            nullable: true
        price:
            type: integer
            nullable: false
        currency:
            type: string
            nullable: false
            length: 3
        playerAchievements:
            type: integer
            column: player_achievements
        overallAchievements:
            type: integer
            nullable: overall_achievements
    oneToMany:
          blogPosts:
              targetEntity: BlogPost
              mappedBy: game
          gameSessions:
              targetEntity: GameSession
              mappedBy: game
              cascade: ["persist", "refresh"]
          purchases:
              targetEntity: Purchase
              mappedBy: game
