App\Entity\GameSession:
    type: entity
    repositoryClass: App\Repository\GameSessionRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
        duration:
            type: integer
        steamUserId:
            type: integer
            column: steam_user_id
    manyToOne:
        game:
            targetEntity: Game
            joinColumn:
                name: game_id
                referencedColumnName: id
