App\Entity\GameSession:
    type: entity
    repositoryClass: App\Repository\GameSessionRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        date:
            type: datetime
        duration:
            type: integer
        day:
            type: datetime
            nullable: true
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referenceColumnName: id
        game:
            targetEntity: Game
            joinColumn:
                name: game_id
                referencedColumnName: id
        gameStats:
            targetEntity: GameStats
            inversedBy: gameSessions
            joinColumn:
                name: game_stats_id
                referenceColumnName: id
