App\Entity\OverallGameStats:
    type: entity
    repositoryClass: App\Repository\OverallGameStatsRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        overallAchievements:
            column: overall_achievements
            type: integer
            nullable: false
        playerAchievements:
            column: player_achievements
            type: integer
            nullable: false
        recentPlaytime:
            column: recent_playtime
            type: integer
            nullable: false
        overallPlaytime:
            column: overall_playtime
            type: integer
            nullable: false
        gameSessions:
            column: game_sessions
            type: integer
            nullable: false
        statusOpen:
            column: status_open
            type: integer
            nullable: false
        statusPaused:
            column: status_paused
            type: integer
            nullable: false
        statusPlaying:
            column: status_playing
            type: integer
            nullable: false
        statusFinished:
            column: status_finished
            type: integer
            nullable: false
        statusGivenUp:
            column: status_given_up
            type: integer
            nullable: false
        numberOfGames:
            column: number_of_games
            type: integer
            nullable: false
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referenceColumnName: id
