App\Entity\PlaytimePerMonth:
    type: entity
    repositoryClass: App\Repository\PlaytimePerMonthRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        month:
            type: datetime
        duration:
            type: integer
        sessions:
            type: integer
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referenceColumnName: id
        gameStats:
            targetEntity: GameStats
            inversedBy: playtimePerMonth
            joinColumn:
                name: game_stats_id
                referencedColumnName: id
