App\Entity\PlaytimePerMonth:
    type: entity
    repositoryClass: App\Repository\PlaytimePerMonthRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        month:
            type: datetime
        duration:
            type: integer
        sessions:
            type: integer
        steamUserId:
            type: bigint
            column: steam_user_id
