App\Entity\PlaytimePerMonth:
    type: entity
    repositoryClass: App\Repository\PlaytimePerMonthRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        month:
            type: datetime
        duration:
            type: integer
        sessions:
            type: integer
        steamUserId:
            type: integer
            column: steam_user_id
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referenceColumnName: id
