App\Entity\Purchase:
    type: entity
    repositoryClass: App\Repository\PurchaseRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 100
        price:
            type: integer
        currency:
            type: string
            length: 3
        notice:
            type: string
            length: 100
            nullable: true
        boughtAt:
            column: bought_at
            type: datetime
            nullable: false
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referenceColumnName: id
        game:
            targetEntity: Game
            joinColumn:
                name: game_id
                referencedColumnName: id
        gameStats:
            targetEntity: GameStats
            inversedBy: purchases
            joinColumn:
                name: game_stats_id
                referencedColumnName: id
