App\Entity\Purchase:
    type: entity
    repositoryClass: App\Repository\PurchaseRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 100
        price:
            type: integer
        currency:
            type: string
            length: 3
        notice:
            type: string
            length: 100
        boughtAt:
            column: bought_at
            type: datetime
            nullable: false
    manyToOne:
        game:
            targetEntity: Game
            inversedBy: purchases
            joinColumn:
                name: game_id
                referencedColumnName: id
