App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        steamId:
            type: bigint
